[build]
publish = "public"
command = "git submodule update --init --recursive && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "git submodule update --init --recursive && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "git submodule update --init --recursive && hugo --gc --minify -b $DEPLOY_PRIME_URL"
